spring:
  application:
    name: demo

resilience4j:
  retry:
    instances:
      api-client:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        exponentialMaxWaitDuration: 10s
        retryExceptionPredicate: com.resilience4j.demo.retry.ApiRetryExceptionPredicate